FROM splunk/splunk:6.5.5

ENV SPLUNK_HEC_QUEUESIZE="500KB" \
SPLUNK_HEC_PERSISTENTQUEUESIZE="0" \
SPLUNK_PARSINGQUEUESIZE="60MB" \
SPLUNK_AGGQUEUESIZE="10MB" \
SPLUNK_TYPINGQUEUESIZE="5MB" \
SPLUNK_INDEXQUEUESIZE="5MB"

COPY ethos-entrypoint.sh /sbin/ethos-entrypoint.sh
RUN chmod +x /sbin/ethos-entrypoint.sh

ENTRYPOINT ["/sbin/ethos-entrypoint.sh"]
CMD ["start-service"]
